/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#f8d8ff",
        "on-background": "#efdbff",
        "surface-container-high": "#322440",
        tertiary: "#deb7ff",
        "surface-bright": "#413350",
        "on-tertiary-fixed": "#2d0050",
        "on-surface": "#efdbff",
        surface: "#1a0d28",
        "inverse-primary": "#9800d0",
        "primary-container": "#bc13fe",
        "secondary-container": "#5f3780",
        "tertiary-fixed": "#f1dbff",
        "primary-fixed-dim": "#ebb2ff",
        background: "#1a0d28",
        "on-error-container": "#ffdad6",
        "surface-variant": "#3d2f4b",
        "surface-container-lowest": "#150822",
        "on-secondary-fixed": "#2e004e",
        "on-secondary-fixed-variant": "#5c347d",
        "inverse-on-surface": "#382a47",
        "surface-dim": "#1a0d28",
        "secondary-fixed": "#f2daff",
        primary: "#ebb2ff",
        "on-primary": "#520072",
        "on-primary-container": "#ffffff",
        "secondary-fixed-dim": "#e0b6ff",
        "on-tertiary-container": "#0c001b",
        "tertiary-container": "#9c51e1",
        "outline-variant": "#504254",
        "error-container": "#93000a",
        "surface-container-highest": "#3d2f4b",
        "on-tertiary-fixed-variant": "#680eac",
        "on-surface-variant": "#d4c0d7",
        secondary: "#e0b6ff",
        "tertiary-fixed-dim": "#deb7ff",
        error: "#ffb4ab",
        "surface-container-low": "#231631",
        outline: "#9d8ba0",
        "inverse-surface": "#efdbff",
        "surface-tint": "#ebb2ff",
        "on-secondary-container": "#d4a6f8",
        "on-primary-fixed-variant": "#74009f",
        "on-primary-fixed": "#320047",
        "surface-container": "#271a35",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Sora", "sans-serif"],
        body: ["Sora", "sans-serif"],
        label: ["Sora", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "14px",
          {
            lineHeight: "1.2",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
      },
    },
  },
  plugins: [],
};
